apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
spec:
  selector:
    app: {{ .Release.Name }}-backend-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.containers.backend.port }}