apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name:  {{ .Release.Name }}-le-crt
spec:
  secretName: tls-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt
  commonName: {{ .Values.host }}
  dnsNames:
  - {{ .Values.host }}