apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: tls-secret
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.containers.frontend.name }}
          servicePort: {{ .Values.containers.frontend.port }}