apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-issuer
spec:
  acme:
    email: vezde.max@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory 
    privateKeySecretRef:
      name: tls-secret-prod
    solvers:
    - http01:
       ingress:
         class: nginx