apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ .Release.Name }}-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory 
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
       ingress:
         class: nginx