apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Values.project }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
