apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-frontend-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.containers.frontend.port }}
